export var TEXT = {
	login_1: 'Por favor ingrese su usuario y contraseña',
	login_2: 'usuario',
	login_3: 'password',
	login_4: 'Login',
	login_5: 'Registrarse',
	login_6: 'He olvidado mi contraseña!',
	registro_1: 'Ingrese sus datos para registrarse',
	registro_2: 'Usuario',
	registro_3: 'Email',
	registro_4: 'Contraseña',
	registro_5: 'Confirmar contraseña',
	registro_6: 'Regsitrarse',
	registro_7: 'Iniciar Sesión',
	recuperar_1: 'Enviaremos un link a su casilla de correo para recuperar su contraseña',
	recuperar_2: 'Email',
	recuperar_3: 'Enviar',
	recuperar_4: 'Iniciar Sesión',
	cambiar_1: 'Ingrese su nueva contraseña',
	cambiar_2: 'Nueva Contraseña',
	cambiar_3: 'Confirmar nueva contraseña',
	cambiar_4: 'Cambiar',
	cambiar_5: 'Iniciar sesión',
	contrasena_cambiada_1: 'Gracias por completar su registro, ya puede loguearse en nuestro sistema!',
	contrasena_cambiada_2: 'Login',
	contrasena_cambiada_3: 'Activación completa',
	error_1: '404 error',
	error_2: 'La página solicitada no se encuentra',
	error_3: 'Inicio',
	message_1 : 'No coincide la verificación de la contraseña',
	message_2 : 'Verificar el link',
	message_3 : 'Contraseña cambiada correctamente',
	message_4 : 'Campo de usuario se encuentra vacío',
	message_5 : 'Campo contraseña se encuentra vacío',
	message_6 : 'El usuario ingresado es inexistente',
	message_7 : 'Contraseña incorrecta',
	message_8 : 'La cuenta no se encuentra activa, por favor ingrese al link enviado a su correo electrónico',
	message_9 : 'El mail ingresado no corresponde a un usuario',
	message_10 : 'Hemos enviado un mail a su casilla de correo electrónico con un link que le permitirá restaurar su contraseña',
	message_11 : 'Hubo un error al enviar el mail',
	message_12 : 'El campo usuario se encuentra vacio',
	message_13 : 'El campo email se encuentra vacio',
	message_14 : 'El campo contraseña se encuentra vacio',
	message_15 : 'La contraseña debe contener al menos 8 caracteres',
	message_16 : 'El campo contraseña y la confirmación de contraseña no son identicos',
	message_17 : 'El usuario que desea crear ya existe',
	message_18 : 'Error al registrar usuario',
	message_19 : 'Usuario creado, se ha enviado un link a su casilla de correo para activar el mismo',
	message_20 : 'Error al enviar mail de verificación',

}